/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./node_modules/@woosign/ui/src/components",
    files: "**/*.native.stories.@(js|jsx|ts|tsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(js|jsx|ts|tsx))$/,
    // @ts-ignore
    req: require.context(
      '../node_modules/@woosign/ui/src/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native\.stories\.(js|jsx|ts|tsx))$/
    ),
  }
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview")
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view: View = global.view;
